[[articles]]
name = "fundamentals"
title = "Fundamentals"

[[articles]]
name = "cookbook"
title = "Cookbook"

[[articles]]
name = "unique-semantics"
title = "Some Unique Semantics"

[[articles]]
name = "effective-elvish"
title = "Effective Elvish"
